load module openmpi-icc/2.0.1 (openmpi)
Traceback (most recent call last):
  File "test-workers.py", line 10, in <module>
    initialize(interface='ib1')
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask_mpi/core.py", line 69, in initialize
    asyncio.get_event_loop().run_until_complete(run_scheduler())
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask_mpi/core.py", line 63, in run_scheduler
    dashboard_address=dashboard_address,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 1335, in __init__
    default_port=self.default_port,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/addressing.py", line 253, in addresses_from_user_args
    host, port, interface, protocol, peer, security, default_port
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/addressing.py", line 284, in address_from_user_args
    host = get_ip_interface(interface)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 188, in get_ip_interface
    "Valid network interfaces are: {}".format(ifname, allowed_ifnames)
ValueError: 'ib1' is not a valid network interface. Valid network interfaces are: ['lo', 'enp5s0f0', 'ib0', 'ib0:0', 'enp5s0f1']
slurmstepd: error: *** JOB 10132136 ON n2080 CANCELLED AT 2020-04-27T12:01:23 DUE TO TIME LIMIT ***
