load module openmpi-icc/2.0.1 (openmpi)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
Traceback (most recent call last):
  File "2020-04-23-AA-fine-scale-vorticity-variance-eNATL60-BLBT02-m03-debug-daskmpi-occigen.py", line 5, in <module>
    initialize()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask_mpi/core.py", line 69, in initialize
    asyncio.get_event_loop().run_until_complete(run_scheduler())
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask_mpi/core.py", line 63, in run_scheduler
    dashboard_address=dashboard_address,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 1066, in __init__
    **kwargs
TypeError: __init__() got an unexpected keyword argument 'interface'
slurmstepd: error: *** JOB 10111556 ON n1989 CANCELLED AT 2020-04-23T23:58:20 DUE TO TIME LIMIT ***
