distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.40.47:40006'
distributed.worker - INFO -       Start worker at:   tcp://10.120.40.47:35759
distributed.worker - INFO -          Listening to:   tcp://10.120.40.47:35759
distributed.worker - INFO -          dashboard at:         10.120.40.47:33687
distributed.worker - INFO - Waiting to connect to:  tcp://10.120.40.134:46661
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  120.00 GB
distributed.worker - INFO -       Local Directory: /tmp/pbs.6093369.admin01/worker-s3r3n7pf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://10.120.40.134:46661
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
=>> PBS: job killed: walltime 1820 exceeded limit 1800
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.40.47:40006'
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 410, in <module>
Traceback (most recent call last):
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
    go()
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 406, in go
    main()
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/softs/rh7/conda/4.5.4/envs/pangeo_full_201909/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 397, in main
    raise TimeoutError("Timed out starting worker.") from None
tornado.util.TimeoutError: Timed out starting worker.
